[package]
authors = ["mdrokz <mohammadmunshi@gmail.com>"]
name = "llama_opencl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llama_cpp_rs = {version = "0.2.0", features = ["opencl"]}